import { Box, Card, Container, Paper, Typography } from "@mui/material";
// import { Swiper, SwiperSlide } from 'swiper/react';
import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import favicon from "./favicon.ico"
import { dancing_script, inter, satisfy } from "@/utils/fonts";
import HomeCover from "@/components/homeCover";

export const metadata: Metadata = {
  title: "Noufal Rahman",
  description: "Generated by create next app",
  icons: [
    {
      url: favicon.src,
    },
  ],
};

async function getAbout() {
  console.log(process.env.NEXT_PUBLIC_STRAPI_API_URI)
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_STRAPI_API_URI}/website?populate[about][populate]=*`
  );
  const { data } = await res.json();
  return data.attributes.about.map((_: any) => _.para);
  // return [
  //   "It's 2002 since I started feeling the Sun. From then, a little kid has grown up fascinating on how the internet and the web works.",
  //   "It's at my age 16 when I developed a conscience about the future of web development and technologies. Back then, I started learning HTML which is my first step towards my passion. I learnt CSS and JS on the go. Once I had completed high school, I got plenty of time (thanks to covid) I learnt them much deeper, the best practices for development and tried out my so far knowledge in development.",
  //   "Today with all the things I need in my hand, I'm efficiently learning and researching much more on the effective working of websites and servers. I believe together we can make the internet a safer place for everyone."
  // ]
}

async function getFeaturedPosts() {
  console.log(process.env.NEXT_PUBLIC_GHOST_API_URI)
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_GHOST_API_URI}/content/posts?key=${process.env.NEXT_PUBLIC_GHOST_CONTENT_API_KEY}&fields=title,slug,feature_image,excerpt,reading_time,created_at&limit=3&filter=featured:true`
  );
  const { posts } = await res.json();
  return posts;
  // return [
  //   {
  //     title: "Hello World",
  //     slug: "hello-world",
  //     feature_image: "https://noufalrahman.dev/images/hello-world.png",
  //     excerpt: "Hello World",
  //     reading_time: 1,
  //     created_at: "2021-09-24T18:30:00.000+05:30"
  //   },
  //   {
  //     title: "Hello World",
  //     slug: "hello-world",
  //     feature_image: "https://noufalrahman.dev/images/hello-world.png",
  //     excerpt: "Hello World",
  //     reading_time: 1,
  //     created_at: "2021-09-24T18:30:00.000+05:30"
  //   },
  //   {
  //     title: "Hello World",
  //     slug: "hello-world",
  //     feature_image: "https://noufalrahman.dev/images/hello-world.png",
  //     excerpt: "Hello World",
  //     reading_time: 1,
  //     created_at: "2021-09-24T18:30:00.000+05:30"
  //   }
  // ]
}

export default async function Home() {
  // const about = await getAbout();
  // const featuredPosts = await getFeaturedPosts();
  // console.log(featuredPosts)
  return (
    <Box>
      <HomeCover />
      <Box
        sx={{
          height: '100vh',
          width: '100%',
          display: 'flex',
          flexFlow: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Typography variant="h1" className={dancing_script.className}>hello</Typography>
        {/* <Typography component="h1" variant="h1" className={inter.className}>
          Noufal Rahman
        </Typography>
        <Typography component="div" variant="h6">
          Penning my life story with nothing but 1s and 0s
        </Typography> */}
      </Box>
      <Box sx={{height: '100vh', width: '100%'}}>
        <Typography variant="h1" textAlign="center" className={satisfy.className}>This is the journey of a kid who dreamed to fly when others crawled </Typography>
      </Box>
      {/* <Paper elevation={12} sx={{ p: 2, mb: 2 }}>
        <Box>
          <Typography variant="h5">About Me</Typography>
          {about.map((para: string, index: number) => (
            <Typography variant="body1" key={`about-para-${index}`} sx={{ my: 2 }}>{para}</Typography>
          ))}
        </Box>
      </Paper> */}
      {/* <Box>
      <FeaturedPosts featured={featuredPosts}/>
      </Box> */}
    
    </Box>
  );
}
